services:
  - type: web
    name: uciip-backend
    env: node
    rootDir: backend
    repo: https://github.com/G-git-22/UCIIP_
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
